name: APK Yapici
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Buildozer Action
        # Bu sürüm en stabil olanıdır efendim:
        uses: ArtemSerebriakov/buildozer-action@v1
        with:
          command: android debug
          repository_display_name: Jarvis

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Jarvis-APK
          path: bin/*.apk
